name: nodejs

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node: [14.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run tsc
      - run: npm test
        env:
          FORCE_COLOR: 1

 
